# config/pipeline_config.yaml
pipeline:
  name: "forex_ml_capstone"

data_range:
  start_date: "2023-01-01"
  end_date: "2026-02-28"

assets:
  # You can add as many pairs here as you want!
  currencies:
    - "EURUSD"
    - "GBPUSD"
  timeframe: "h1"

aws:
  s3_bucket: "forex-datalake-bucket"
  raw_prefix: "raw/dukascopy/"